spring:
  datasource:
    url: jdbc:h2:mem:password_validation
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
